"""Render memorus bullets (team + personal) into a read-only Obsidian vault layout.

Vault layout produced:
    <vault>/memorus/team/<bullet_id>.md      # team bullets from TeamCacheStorage
    <vault>/memorus/personal/<bullet_id>.md  # personal bullets from Memory.search

Files are overwritten on each run. They carry a "do not edit" banner; user
edits will be reverted on the next sync. To submit new knowledge, write to
<vault>/memorus/inbox/*.md (handled by watcher.InboxWatcher).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from memorus.obsidian_adapter.frontmatter import dump as fm_dump

logger = logging.getLogger(__name__)

_BANNER = (
    "<!-- AUTO-GENERATED by memorus.obsidian_adapter. "
    "Edits will be reverted on next sync. -->"
)
_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]+")


def _safe_filename(stem: str) -> str:
    cleaned = _SAFE_NAME.sub("-", stem).strip("-")
    return cleaned[:80] or "bullet"


def _bullet_to_meta(bullet: Any, *, kind: str) -> dict[str, Any]:
    """Flatten a TeamBullet / BulletMetadata pydantic model into YAML-safe dict."""
    if hasattr(bullet, "model_dump"):
        raw = bullet.model_dump(mode="json", exclude_none=True)
    elif isinstance(bullet, dict):
        raw = dict(bullet)
    else:
        raw = {k: v for k, v in vars(bullet).items() if not k.startswith("_")}
    meta: dict[str, Any] = {"kind": kind}
    meta.update(raw)
    meta.pop("content", None)  # body holds content
    return meta


def _write_bullet_file(out_dir: Path, stem: str, meta: dict[str, Any], body: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{_safe_filename(stem)}.md"
    content = fm_dump(meta, f"{_BANNER}\n\n{body}")
    target.write_text(content, encoding="utf-8")
    return target


@dataclass
class ExportSummary:
    team_written: int = 0
    personal_written: int = 0


class VaultExporter:
    """Render memorus knowledge into a vault directory.

    Construct with the vault root; call ``export()`` to refresh both team
    and personal mirrors. Either source may be ``None`` to skip that pool.
    """

    def __init__(
        self,
        vault_root: Path | str,
        *,
        team_cache: Any | None = None,
        personal_memory: Any | None = None,
        personal_query: str = "",
        personal_limit: int = 500,
    ) -> None:
        self._root = Path(vault_root) / "memorus"
        self._team_cache = team_cache
        self._personal = personal_memory
        self._personal_query = personal_query
        self._personal_limit = personal_limit

    def export(self) -> ExportSummary:
        summary = ExportSummary()
        if self._team_cache is not None:
            summary.team_written = self._export_team()
        if self._personal is not None:
            summary.personal_written = self._export_personal()
        logger.info(
            "Vault export: team=%d personal=%d at %s",
            summary.team_written, summary.personal_written, self._root,
        )
        return summary

    # -- team --------------------------------------------------------------

    def _iter_team_bullets(self) -> Iterable[tuple[str, Any]]:
        cache = self._team_cache
        # Public method first; fall back to documented private attr.
        if hasattr(cache, "iter_bullets"):
            yield from cache.iter_bullets()
            return
        bullets = getattr(cache, "_bullets", None)
        if isinstance(bullets, dict):
            for bid, bullet in bullets.items():
                yield bid, bullet
            return
        logger.warning("team_cache has no iterable bullet collection; skipping")

    def _export_team(self) -> int:
        out_dir = self._root / "team"
        n = 0
        for bid, bullet in self._iter_team_bullets():
            meta = _bullet_to_meta(bullet, kind="team")
            body = getattr(bullet, "content", "") or meta.pop("content", "") or ""
            _write_bullet_file(out_dir, str(bid), meta, body)
            n += 1
        return n

    # -- personal ----------------------------------------------------------

    def _export_personal(self) -> int:
        out_dir = self._root / "personal"
        result = self._personal.search(
            self._personal_query, limit=self._personal_limit
        )
        items = result.get("results", []) if isinstance(result, dict) else []
        n = 0
        for item in items:
            bid = str(item.get("id") or item.get("hash") or n)
            body = item.get("memory") or item.get("content") or ""
            meta = {k: v for k, v in item.items() if k not in ("memory", "content")}
            meta["kind"] = "personal"
            _write_bullet_file(out_dir, bid, meta, body)
            n += 1
        return n
