"""Tests for team playbook index.md generator (STORY-R093)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest

from memorus.team.export import generate_index_md, write_index_md


# Fixed timestamp for deterministic tests.
FIXED_NOW = datetime(2026, 4, 23, 10, 15, 0, tzinfo=timezone.utc)


def _bullet(**kwargs):
    base = {
        "content": "hello",
        "tag": "python",
        "recall_count": 1,
        "decay_weight": 0.5,
        "created_at": "2026-01-01T00:00:00Z",
    }
    base.update(kwargs)
    return base


# ---------------------------------------------------------------------------
# Header & empty playbook
# ---------------------------------------------------------------------------

def test_empty_playbook_produces_legal_index():
    out = generate_index_md([], "team:backend", now=FIXED_NOW)
    assert out.startswith("# Team Playbook Index\n")
    assert "**Total bullets:** 0" in out
    assert "**Scope:** team:backend" in out
    assert "**Last updated:** 2026-04-23T10:15:00Z" in out
    assert out.endswith("\n")
    # No tag groups should appear.
    assert "## " not in out
    # Footer present.
    assert "Auto-generated index" in out


def test_header_fields_exact():
    out = generate_index_md(
        [],
        "team:backend",
        generator="memorus 0.2.2",
        embedding_model="all-MiniLM-L6-v2",
        embedding_dim=384,
        now=FIXED_NOW,
    )
    assert "**Scope:** team:backend" in out
    assert "**Total bullets:** 0" in out
    assert "**Last updated:** 2026-04-23T10:15:00Z" in out
    assert "**Embedding model:** all-MiniLM-L6-v2 (dim=384)" in out
    assert "**Generated by:** memorus 0.2.2" in out


# ---------------------------------------------------------------------------
# Grouping and ordering
# ---------------------------------------------------------------------------

def test_groups_sorted_alphabetically():
    bullets = [
        _bullet(tag="rust", content="r1"),
        _bullet(tag="ansible", content="a1"),
        _bullet(tag="python", content="p1"),
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    i_ansible = out.index("## ansible")
    i_python = out.index("## python")
    i_rust = out.index("## rust")
    assert i_ansible < i_python < i_rust


def test_intra_group_sorted_by_recall_desc_then_created_asc():
    bullets = [
        _bullet(tag="python", content="low-old", recall_count=1,
                created_at="2025-01-01T00:00:00Z"),
        _bullet(tag="python", content="high-new", recall_count=10,
                created_at="2026-01-01T00:00:00Z"),
        _bullet(tag="python", content="high-old", recall_count=10,
                created_at="2024-01-01T00:00:00Z"),
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    # Expected order: high-old, high-new, low-old
    i_ho = out.index("high-old")
    i_hn = out.index("high-new")
    i_lo = out.index("low-old")
    assert i_ho < i_hn < i_lo


def test_group_header_includes_count():
    bullets = [
        _bullet(tag="python", content="p1"),
        _bullet(tag="python", content="p2"),
        _bullet(tag="rust", content="r1"),
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "## python (2)" in out
    assert "## rust (1)" in out


def test_tag_precedence_falls_back_to_tags_then_section():
    bullets = [
        {"content": "a", "tags": ["python", "other"], "recall_count": 0},
        {"content": "b", "section": "rust", "recall_count": 0},
        {"content": "c", "recall_count": 0},  # falls back to "general"
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "## python (1)" in out
    assert "## rust (1)" in out
    assert "## general (1)" in out


# ---------------------------------------------------------------------------
# Bullet formatting
# ---------------------------------------------------------------------------

def test_bullet_format_basic():
    bullets = [_bullet(content="foo", recall_count=7, decay_weight=0.94)]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "- `[#7]` foo *(weight: 0.94)*" in out


def test_bullet_format_with_sources():
    bullets = [_bullet(content="foo", recall_count=7, decay_weight=0.94,
                       sources_count=3)]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "- `[#7]` foo *(weight: 0.94, sources: 3)*" in out


def test_bullet_format_with_source_refs_list():
    bullets = [_bullet(content="foo", recall_count=7, decay_weight=0.94,
                       source_refs=["a", "b", "c", "d", "e"])]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "sources: 5" in out


def test_bullet_format_without_sources_omits_suffix():
    # No sources-related field at all — suffix omitted cleanly.
    bullets = [_bullet(content="foo", recall_count=7, decay_weight=0.94)]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "sources" not in out.split("foo", 1)[1].split("\n", 1)[0]


# ---------------------------------------------------------------------------
# Escaping
# ---------------------------------------------------------------------------

def test_markdown_special_chars_escaped():
    bullets = [_bullet(content="use `foo` *and* [bar] and _baz_")]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    # Backslash-escaped forms.
    assert r"\`foo\`" in out
    assert r"\*and\*" in out
    assert r"\[bar\]" in out
    assert r"\_baz\_" in out


def test_backslash_itself_escaped():
    bullets = [_bullet(content=r"path\to\file")]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert r"path\\to\\file" in out


# ---------------------------------------------------------------------------
# Unicode truncation
# ---------------------------------------------------------------------------

def test_unicode_truncation_code_points_not_bytes():
    # 200 Chinese chars = 600 UTF-8 bytes; truncation should use code points.
    content = "中" * 200
    bullets = [_bullet(content=content)]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    # Should contain exactly 120 "中" characters in the bullet line.
    line = [l for l in out.splitlines() if "中" in l][0]
    assert line.count("中") == 120


def test_unicode_truncation_short_content_unchanged():
    bullets = [_bullet(content="short")]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "short" in out


def test_unicode_truncation_emoji_counted_by_code_points():
    # 200 emoji each 1 code point (BMP-style heart); truncate to 120.
    content = "❤" * 200
    bullets = [_bullet(content=content)]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    line = [l for l in out.splitlines() if "❤" in l][0]
    assert line.count("❤") == 120


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------

def test_deterministic_same_input_same_output():
    bullets = [
        _bullet(tag="python", content="p1", recall_count=3),
        _bullet(tag="rust", content="r1", recall_count=5),
        _bullet(tag="python", content="p2", recall_count=3,
                created_at="2026-02-01T00:00:00Z"),
    ]
    a = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    # Shuffle input order — result must be identical.
    b = generate_index_md(list(reversed(bullets)), "team:x", now=FIXED_NOW)
    assert a == b


def test_trailing_newline_present():
    out = generate_index_md([], "team:x", now=FIXED_NOW)
    assert out.endswith("\n")
    assert not out.endswith("\n\n\n")


# ---------------------------------------------------------------------------
# write_index_md
# ---------------------------------------------------------------------------

def test_write_index_md_creates_directory(tmp_path: Path):
    out_dir = tmp_path / "nested" / ".ace"
    assert not out_dir.exists()
    target = write_index_md([], "team:x", out_dir, now=FIXED_NOW)
    assert target == out_dir / "index.md"
    assert target.exists()
    assert target.read_text(encoding="utf-8").startswith("# Team Playbook Index")


def test_write_index_md_roundtrip(tmp_path: Path):
    bullets = [_bullet(content="alpha"), _bullet(tag="rust", content="beta")]
    target = write_index_md(bullets, "team:x", tmp_path, now=FIXED_NOW)
    text = target.read_text(encoding="utf-8")
    expected = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert text == expected


# ---------------------------------------------------------------------------
# Golden snapshot for cross-language byte diff
# ---------------------------------------------------------------------------

GOLDEN_BULLETS = [
    {
        "content": "Always use pnpm install --frozen-lockfile in CI",
        "tag": "python",
        "recall_count": 18,
        "decay_weight": 0.94,
        "created_at": "2026-01-10T00:00:00Z",
        "sources_count": 5,
    },
    {
        "content": "Prefer pathlib.Path over os.path",
        "tag": "python",
        "recall_count": 12,
        "decay_weight": 0.88,
        "created_at": "2026-02-01T00:00:00Z",
        "sources_count": 3,
    },
    {
        "content": "Use #[non_exhaustive] on public enums reserved for growth",
        "tag": "rust",
        "recall_count": 22,
        "decay_weight": 0.91,
        "created_at": "2026-01-20T00:00:00Z",
        "sources_count": 4,
    },
]


def test_golden_snapshot():
    out = generate_index_md(
        GOLDEN_BULLETS,
        "team:backend",
        generator="memorus 0.0.0-test",
        embedding_model="all-MiniLM-L6-v2",
        embedding_dim=384,
        now=FIXED_NOW,
    )
    # Check structural invariants we rely on for cross-language parity.
    expected = (
        "# Team Playbook Index\n"
        "\n"
        "**Scope:** team:backend\n"
        "**Total bullets:** 3\n"
        "**Last updated:** 2026-04-23T10:15:00Z\n"
        "**Embedding model:** all-MiniLM-L6-v2 (dim=384)\n"
        "**Generated by:** memorus 0.0.0-test\n"
        "\n"
        "---\n"
        "\n"
        "## python (2)\n"
        "\n"
        "- `[#18]` Always use pnpm install --frozen-lockfile in CI *(weight: 0.94, sources: 5)*\n"
        "- `[#12]` Prefer pathlib.Path over os.path *(weight: 0.88, sources: 3)*\n"
        "\n"
        "## rust (1)\n"
        "\n"
        "- `[#22]` Use #\\[non\\_exhaustive\\] on public enums reserved for growth *(weight: 0.91, sources: 4)*\n"
        "\n"
        "---\n"
        "\n"
        "*Auto-generated index — do not edit manually. Regenerate via `memorus export --team`.*\n"
    )
    assert out == expected


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------

def test_missing_recall_count_defaults_to_zero():
    bullets = [{"content": "x", "tag": "python", "decay_weight": 0.5}]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "`[#0]`" in out


def test_missing_decay_weight_defaults_to_one():
    bullets = [{"content": "x", "tag": "python", "recall_count": 0}]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert "weight: 1.00" in out


def test_created_at_accepts_datetime_object():
    dt = datetime(2026, 5, 1, tzinfo=timezone.utc)
    bullets = [
        _bullet(tag="python", content="old", recall_count=5, created_at=dt),
        _bullet(tag="python", content="new", recall_count=5,
                created_at="2026-06-01T00:00:00Z"),
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    assert out.index("old") < out.index("new")


def test_chinese_tag_sorts_and_renders():
    bullets = [
        _bullet(tag="python", content="p"),
        _bullet(tag="中文", content="c"),
    ]
    out = generate_index_md(bullets, "team:x", now=FIXED_NOW)
    # Both headings exist.
    assert "## python" in out
    assert "## 中文" in out
